<?php

namespace app\admin\controller;

class Article extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }



    public function lst()
    {
        return $this->fetch();
    }

    public function add()
    {
        $cate = model('cate');
        $article = model('article');
        if($_POST){
            //var_dump($_POST);
//            dump(input('post.'));
//            die();
            if($article->addArticle(input('post.'))){
                $this->success('文章添加成功',url('lst'),'','1');
            }else{

                $this->error('文章添加失败',url('add'));
            }
            return;
        }
        $data = $cate->getCate();
        $res= $cate->sort($data);
        $this->assign('cateres',$res);

        return $this->fetch();
    }

    public function edit()
    {
        return $this->fetch();
    }


}
