<?php

namespace app\admin\controller;

class Article extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }



    public function lst()
    {
        $article = model('article');
//        $res= db('article')->field('a.*,b.catename')->alias('a')->join('bk_cate b','a.cateid=b.id')->paginate(5);
        $res = $article->getArticle();
        //dump($res);die();
        $this->assign('articles',$res);
        return $this->fetch();
    }

    public function add()
    {
        $cate = model('cate');
        $article = model('article');
        if($_POST){
            //var_dump($_POST);
//            dump(input('post.'));
//            die();
            if($article->addArticle(input('post.'))){
                $this->success('文章添加成功',url('lst'),'','1');
            }else{

                $this->error('文章添加失败',url('add'));
            }
            return;
        }
        $data = $cate->getCate();
        $res= $cate->sort($data);
        $this->assign('cateres',$res);

        return $this->fetch();
    }

    public function edit()
    {
        return $this->fetch();
    }

    public function del(){
        if(input('id')){
            $cate = model('article');
            if($cate->del(input('id'))){
                $this->success('文章删除成功',url('lst'));
            }else{
                $this->error('文章删除失败',url('lst'));
            }
        }
    }

}
