<?php
/**
 * Created by PhpStorm.
 * User: kain
 * Date: 2017/9/21
 * Time: 21:18
 */

namespace app\admin\controller;

use think\Controller;

class Base extends Controller
{
    /**
     *  公共初始化方法
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('id') || !session('name')){
            $this->error('您尚未登录系统','login/index');
        }
    }
}