<?php

namespace app\admin\controller;

class Cate extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /* public function _initialize(){
         $admin = model('admin');
     }*/

    public function lst()
    {
        $admin = model('cate');
        $res = $admin->getAdmin();
//        dump($res) ;
//        die();
        $this->assign('adminres',$res);

        return $this->fetch();
    }

    public function add(){
        if($_POST){
            //var_dump($_POST);
            $cate = model('cate');
            if($cate->addCate(input('post.'))){
                $this->success('栏目添加成功',url('lst'));
            }else{

                $this->error('栏目添加失败',url('add'));
            }
            return;
        }
        return $this->fetch();
    }

}
