<?php

namespace app\admin\controller;

class Link extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /* public function _initialize(){
         $admin = model('admin');
     }*/

    public function lst()
    {
        $admin = model('Link');
        $res = $admin->getLink();
        if($_POST){
//            dump(input('post.'));
//            die();
            $res = $admin->getLink(input('post.'));
        }

        $this->assign('linkres',$res);

        return $this->fetch();
    }

    public function add()
    {
        if($_POST){
            //var_dump($_POST);
            $admin = model('link');
            if($admin->addLink($_POST)){
                $this->success('超链接添加成功',url('lst'));
            }else{
                $this->error('超链接添加失败',url('add'));
            }
            return;
        }
        return $this->fetch();
    }

    public function edit($id)
    {
        if($_POST){
            $link = model('link');
            if($link->editLink(input('post.'))){
                $this->success('超链接修改成功',url('lst'));
            }else{

                $this->error('超链接修改失败');
            }
            return;
        }
        $link = db('link')->find($id);
        $this->assign('links',$link);
        return $this->fetch();
    }

    public function del($id){
        $link = model('link');
        if($link->del($id)){
            $this->success('超链接删除成功',url('lst'));
        }else{
            $this->error('超链接删除失败');
        }
    }
}
